# Run workflow on every push to main
on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code from the main branch
        - uses: actions/checkout@v2
      # sets up .NET Core SDK 3.1
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v1.7.2
          with:
            # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
            dotnet-version: 3.1
      # publishes Blazor project to the release-folder
        - name: Publish .Net Core Project
          run: dotnet publish blazor-dads-text-adventure.csproj -c Release -o release --nologo
      # Changes base-tag in html to point to correct location
        - name: Modify base-tag in index.html to point to repository
          run: sed -i 's/<base href="\/" \/>/<base href="blazor-dads-text-adventure\/" \/>/g' release/wwwroot/index.html
      # add .nojekyll file to avoid Jekyll build since it is unnecessary
        - name: Add .nojekyll file
          run: touch release/wwwroot/.nojekyll
      # Commit release to GitHub Pages
        - name: Commit wwwroot to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@3.7.1
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: release/wwwroot
      
